---
title: "Lesson Plan"
output: html_document
Authors: Soren A. Christensen, Rachel Lo, Brian Reed
---

## Introduction

Background

Significance/applications in the real world

Why spatial statistics are so different from what we're used to.

## Objectives

Introduce this area of statistics to calss, give them exposure.

Be familiar to applciations of the package.

Talk briefly about other packages.

Show how this is applicable to being an analyst in the air force.

## Example

Deer data. ???

## Readings

Materials for the students to review before class, and use as refernces while doing the homework.

An brief article which addresses the importance of spatial analysis in the world. This is improtant for the students to understand why this topic is being addressed. 

http://www.nytimes.com/2015/01/09/business/international/mapping-the-worlds-problems.html

This is an introductory vignette for basic exercises using adehabitatHR.

http://cran.r-project.org/web/packages/adehabitatHR/vignettes/adehabitatHR.pdf

Main CRAN webpage for adehabtiatHR

http://cran.r-project.org/web/packages/adehabitatHR/index.html

## Homework Questions

Manipulating data with adehabitat

## References

Other references that might be useful

https://sites.google.com/site/rodriguezsanchezf/news/usingrasagis

https://www.movebank.org/node/14620

http://www.rdocumentation.org/packages/adehabitat

http://core.ac.uk/download/pdf/26815643.pdf

http://cran.r-project.org/web/packages/adehabitat/adehabitat.pdf

http://www.mikemeredith.net/blog/1212_Data_for_home_range_analysis_in_R.htm#1

http://cran.r-project.org/web/packages/adehabitatHR/vignettes/adehabitatHR.pdf